{
 "title": "Single Tracelet Details",
 "time": { "from": "now-1y/y", "to": "now-1y/y" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tracelet", "query": { "query": "label_values(device)" } }
  ]
 },
 "panels": [
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fw{job=\"tracelet\", device=\"$tracelet\"}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Wifi Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "wifi_rssi_dbm{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "wifi_ap{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected to Localization Server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "lsi_is_connected{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Missing Acks from Localization Server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "lsi_acks_missed{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected to NTRIP Caster",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ntrip_is_connected{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Fused", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Sensor Fusion State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sensor_fusion_state{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GNSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Satellites in view",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "gnss_num_sats{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "{{system}}"
    },
    {
     "expr": "gnss_num_sv{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "sats_used"
    }
   ]
  },
  {
   "title": "GNSS Reference Station",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "ubx_ref_station_id{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor Fusion Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "ubx_sensor_fusion_status_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Programmable Gain Amplifier",
   "type": "timeseries",
   "description": "Shows gain of PGAs for each RF Block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "gnss_pga{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "gnss_heading{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{info}}"
    }
   ]
  },
  {
   "title": "Fix Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "gnss_fix_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Boot Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "ubx_boot_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "gnss_eph_meters{job=\"tracelet\", device=\"$tracelet\"} < 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "ubx_runtime{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GNSS Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "gnss_ground_speed{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protection Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "gnss_protection_level{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{info}}"
    }
   ]
  },
  { "title": "UWB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "UWB Fix Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "uwb_fix_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "X-Position (m)",
   "type": "timeseries",
   "description": "UWB X position (m)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "uwb_x_meters{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "uwb_is_valid{job=\"tracelet\", device=\"$tracelet\"} * 10",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Horizontal position error (m)",
   "type": "timeseries",
   "description": "UWB estimated horizontal position error (m)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "uwb_eph_meters{job=\"tracelet\", device=\"$tracelet\"} < 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Y-Position (m)",
   "type": "timeseries",
   "description": "UWB Y position (m)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "uwb_y_meters{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Position validity",
   "type": "timeseries",
   "description": "UWB position is valid (True/False)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "uwb_is_valid{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tacho", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Vehicle Speed (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "speed_meters_per_second{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milage (km)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mileage_meters{job=\"tracelet\", device=\"$tracelet\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "System Time Change Rate",
   "type": "timeseries",
   "description": "Should be around 1",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(system_time_seconds{job=\"tracelet\", device=\"$tracelet\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "SNTP Update",
   "type": "barchart",
   "description": "Should be around 1 per hour",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "changes(sntp_updates{job=\"tracelet\", device=\"$tracelet\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "health{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GNSS UART Errors",
   "type": "timeseries",
   "description": "Should be around 1 per hour",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "gnss_uart_errors{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "free_heap_bytes{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UBX IMU Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubx_temperature_degrees{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ignition",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ignition_state{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}